### ISSUE TITLE
After the channel ticket id is saved | the id should change into a link that can be edited

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#108]
The channel listing id should change into a link once saved that can be edited. 

Ex : should follow the same behavior like channel ticket id

![20](https://cloud.githubusercontent.com/assets/11714762/19561094/dc3f1bfa-96f4-11e6-87d2-fcc1c04a618f.png)

current : 
![20](https://cloud.githubusercontent.com/assets/11714762/19561177/2ee6f7a6-96f5-11e6-8f37-7146af6e87e6.png)

**Comment by robiulpro** [comment]
Fixed.

**Comment by Divyagawas** [comment]
- The channel listing Id changes to a link only on refresh
- The edited channel listing id not saved/shows. Shows on refresh
![image](https://cloud.githubusercontent.com/assets/11714762/19643617/c66f8b86-9a08-11e6-8628-4874fbee9d6f.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
Tested
