### ISSUE TITLE
The count of sku's on the catalog summary is incorrect for the all the attempts other than the 1st one

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#13]
The following is the summary section for a catalog for attempt 5.
The fields such as total sku's, to be reviewed, total reviewed, review pass and info pending with AE does not show the count along with the Sku which have be reviewed  in the previous attempt

![image](https://cloud.githubusercontent.com/assets/11714762/19260370/9d35ee66-8fa6-11e6-8df5-b433d5d7840d.png)

**Comment by robiulpro** [comment]
This count is for current attempt (not all attempt). As discussed we will show total reviewed count separately @Divyagawas , @ashika123
