### ISSUE TITLE
Single SKU | Field level sku's should be highlighted

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#133]
In the following sku, there is one numeric validation error(which is highlighted on the summary) and 2 field level validation error (Not highlighted on the summary)

This needs to be highlighted at the single sku level
![25](https://cloud.githubusercontent.com/assets/11714762/19714942/8c71254e-9b6f-11e6-921c-7d66ab2a9dc5.png)

**Comment by robiulpro** [comment]
Fixed
