### ISSUE TITLE
LE can download all the SKU's in the catalog when clicked on "All" tab

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#135]
Currently: LE can download all the SKU's in the catalog when clicked on "all" tab.
Expected: LE should be able to download only those products which are "to be reviewed" when clicked on "All" tab

![image](https://cloud.githubusercontent.com/assets/11714762/19758426/9e08152a-9c45-11e6-94d6-39564ce0880f.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
Tested
