### ISSUE TITLE
The ticket status while changing to "partial listed", "sent to channel" or "info pending with AE" from the "next action" dropdown, does not check if the "channel ticket id" is added or not

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#14]
1. AE has been assigned a ticket - status is "not started"
2. Now AE changes the status to "work in progress"
3. Now there appears a input box for "channel ticket id" and "next action" dropdown.
4. Without adding the "channel ticket id" AE can now change the status to "seller panel down"
5. Once the status is seller panel down, the next option shows the status work in progress, sent to channel,  partially listed and info pending with AE.
6. Now if AE chooses  "sent to channel", "partially listed" or "info pending with AE"  - The status gets saved.

Expected: When the status of ticket is changed to "sent to channel", "partially listed" or "info pending with AE" it should check whether channel ticket id is added or not. if not should give a message "please add channel ticket id"

![12](https://cloud.githubusercontent.com/assets/11714762/19260869/d9e695f0-8faa-11e6-8021-f298a6e169d3.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
Fixed
