### ISSUE TITLE
Catalog action history

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#149]
This is like an activity tab which jots down the time and the action that is performed on it.

Comments need not be included in it.
Keep a check on the time and date that is entered.

Reference is attached

Have to check if this is possible using Disqus

ex: example UI
![capture 1](https://cloud.githubusercontent.com/assets/11714762/21006567/6ba88200-bd5f-11e6-99ad-9bdd0e022969.JPG)

**Comment by robiulpro** [comment]
Completed
