### ISSUE TITLE
The catalog status when changed to "review fail" it can be seen under "all catalogs" but is not listed under "unassigned " tab for AE and LE

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#15]
The catalog status when changed to "review fail" it can be seen under "all catalogs" but is not listed under "unassigned " tab for AE and LE

For the example below, a catalog has a status "review fail" which can be seen under "all catalogs tab"
![12](https://cloud.githubusercontent.com/assets/11714762/19262042/65bc109e-8fb2-11e6-90b4-4f5091b36ce8.png)

But this catalog is not listed under "unassigned" tab
![image](https://cloud.githubusercontent.com/assets/11714762/19262062/7bf4ec6e-8fb2-11e6-838f-1f90b08736cd.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
Fixed
