### ISSUE TITLE
If market places does not have checklist - the checklist on pop up is missaligned

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#158]
http://listr.browntape.com/catalogs/view/7
![image](https://cloud.githubusercontent.com/assets/11714762/20422639/98330850-ad91-11e6-89eb-700517022ae4.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
![image](https://cloud.githubusercontent.com/assets/11714762/20519615/a58baf44-b0c9-11e6-9d5e-35ebda15318a.png)
