### ISSUE TITLE
The 'created time' and 'updated time' is incorrect for the moved catalogs

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#161]
Created a new catalog
Selected the error sku's in the catalog and moved to the a new catalog
On catalog listing page the created date and last updated date for that catalog is shown incorrect

![0](https://cloud.githubusercontent.com/assets/11714762/20428364/abbd9d14-adae-11e6-86ce-c23f16516e60.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
Tested
