### ISSUE TITLE
catalog single page | summary | catalog status with the attempts needs to be aligned properly

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#17]
![image](https://cloud.githubusercontent.com/assets/11714762/19267942/353240b6-8fcf-11e6-857b-ed15eedc2728.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
can you please reduce the space between status and attempts. Would like the same spacing as in between bt category and field count below it

![image](https://cloud.githubusercontent.com/assets/11714762/19311614/c59eda82-90ac-11e6-9be0-8e5200062b75.png)

**Comment by Divyagawas** [comment]
Fixed.

**Comment by nevesseq** [comment]
fixed, have reduce the space between status & attempts

**Comment by Divyagawas** [comment]
Tested.Thanx
