### ISSUE TITLE
channel category | level 1 category cannot be searched in 'Add maprket place' pop up

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#171]
Whenever we add a market place we have to mention the category noding but for certain market place we only have 'level 1' category
like jabong and myntra. We are unable to fill this category in it.

Need that to be fixed as we cannot proceed with that market place unless the noding is filled

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
Tested
