### ISSUE TITLE
For breach in ( Ticket SLA to AE , LA & LE  , Catalog SLA to AE, LA & LE)

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#178]
Notification for the breaching the deadline to review the catalog or ticket

The SLA breach should be a kind of highlight or a blink on the catalog / listing ticket list page as well as inside on their respective pages.

For the first time whenever:
Case 1: Breach in assigning the catalog/ ticket SLA
Action: Notify AE and LA

Case 2: Breach in Catalog review / ticket SLA
Action: Notify LA, AE and LE

Only a single mailer notification will go.

Mail Subject: Breach in 'Assign' or 'Catalog Review' or 'Listing ticket' SLA
Body: 
Details about catalog or listing ticket along with creation date.

-------------------------------------------------------------

Assigning Catalog SLA:
1 day for all the Market Places

Assigning Listing Ticket SLA:
1 day for all the Market Places

Catalog Review SLA:
3 hrs for all the Market Places

Listing Ticket SLA:

Amazon india	- 3days
Amazon US- 10days
Amazon UK- 10days
Ask me Bazaar- 8days
Big commerce-8days
Craftsvilla- 4days
eBay- 3days
Fashionara- 8days
Firstcry- 15days
Flipkart- 11days
HomeShop18- 16days
Jabong- 24days
Kartmagic- 10days
Kartrocket- 10days
Limeroad	- 15days
Magento- 10days
Mirraw- 16days
Mr.Voonik- 15days
Myntra- 25days
Naaptol.com- 10days
Offline Store- 10days
OpenCart- 10days
PayPal- 10days
Paytm- 11days
Pepperfry- 15days
Rediff Shopping- 8days
ShopClues- 8days
Shopify- 8days
Snapdeal.com- 14days
Tradus- 8days
Voonik- 15days
Vilara- 16days
Woocommerce- 8days
Zepo- 8days

**Comment by robiulpro** [comment]
Completed
