### ISSUE TITLE
The error message displayed on uploading a catalog shows html tags

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#182]
1. Log in as AE
2. Open a catalog in info pending status
3. Download the 'Info pending' sku's
4. Edit one sku id in the excel sheet and upload again
5. Shows correct error message - But is displayed along with the html tags

![33](https://cloud.githubusercontent.com/assets/11714762/20587108/5f8746e4-b230-11e6-8ec0-cf9307c5fb7b.png)

**Comment by robiulpro** [comment]
FIxed

**Comment by Divyagawas** [comment]
tested
