### ISSUE TITLE
Catalog (Status:Info pending) | Uploading a catalog with a new SKU does not show any error message

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#183]
1. Log in as AE
2. Open a catalog in info pending status
3. Download the 'Info pending' sku's
4. Add one more sku in the excel sheet and upload again
5. The upload box gets stuck and if clicked on 'upload catalog' shows a success message 
![33](https://cloud.githubusercontent.com/assets/11714762/20587197/647e3eae-b231-11e6-9410-961aba185f5d.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by robiulpro** [comment]
FIxed

**Comment by Divyagawas** [comment]
Tested
