### ISSUE TITLE
Catalog (Status:Draft) | Uploading a catalog with the same sku's again does not show a success message

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#186]
Log in as AE
Open a catalog in draft status
Click on upload and upload the same sheet (With some changes in SKU attributes)
The upload box gets stuck and does not show a success message
(Simplar to #183)

![image](https://cloud.githubusercontent.com/assets/11714762/20588104/99e16650-b238-11e6-82a0-24a0fba95ca8.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
fixed
