### ISSUE TITLE
Catalog(Status:Draft)| Edit mode | if accessed by LE - Some values displayed on top of the table

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#187]
![image](https://cloud.githubusercontent.com/assets/11714762/20589356/f19a74d2-b241-11e6-9bf3-b225e55e5afb.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
In draft mode LE should not be able to see the skus
Catalog in draft mode: logged in as LE(Robiul)
![image](https://cloud.githubusercontent.com/assets/11714762/20625740/412c37ca-b33b-11e6-9708-c4463bdff45f.png)
