### ISSUE TITLE
Error message Ui breaks

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#193]
![44](https://cloud.githubusercontent.com/assets/11714762/20625520/d34c835a-b339-11e6-90e5-e7f1e6b10778.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
This has not been fixed
![image](https://cloud.githubusercontent.com/assets/11714762/21284917/a855dc7e-c44f-11e6-969a-15511c3c35e7.png)
