### ISSUE TITLE
interface for - Access to CA to add/update category deactivation time

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#204]
LA can currently see the deactivation date
Next to this date create a 'edit' button - which on click will make the deactivation field editable.
When the deactivation date feild is editable - add one save (icon) and cancel (icon)
the editable feild should open up a calendar.
On clicking on save(icon) -should save
On clicking on cancel(icon) -should cacel

**Comment by nevesseq** [comment]
done
