### ISSUE TITLE
Catalog>Listing ticket > on clicking the ticket id, should not open on the same tab

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#209]
Currently on clicking the listing ticket, it is opening on the same page instead of new tab. 
This needs to be rectified.
![2nddec](https://cloud.githubusercontent.com/assets/11714762/20834056/0e327680-b8b9-11e6-9e4a-c9692b68a64b.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
tested
