### ISSUE TITLE
Ticket created email does not show any data

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#24]
Ticket created email does not show any data from the document https://docs.google.com/document/d/1-AAVfEaStjpPmYHWHvjQZ0Uw2Ui7VQxzfaz18C4cgTk/edit

![image](https://cloud.githubusercontent.com/assets/11714762/19271273/937f0386-8fe1-11e6-80b9-ebcaefd8692f.png)

**Comment by robiulpro** [comment]
Fixed.

**Comment by Divyagawas** [comment]
Fixed.Thanx
