### ISSUE TITLE
Next action field on all the pages is miss aligned

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#25]
![12](https://cloud.githubusercontent.com/assets/11714762/19271451/67393336-8fe2-11e6-8085-9195ff79d1ef.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
Still seems to be missaligned
![image](https://cloud.githubusercontent.com/assets/11714762/19312256/421b845a-90af-11e6-8080-6d90674f8927.png)

**Comment by Divyagawas** [comment]
Fixed
