### ISSUE TITLE
After the catalog name is clicked - on hovering the same catalog name (only the first alphabel is underlined)

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#259]
![truncating](https://cloud.githubusercontent.com/assets/11714762/21585568/f9c30ac8-d0e8-11e6-8fc7-0a7040c7bcb4.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
On hovering does not show the catalog name in a pop over
