### ISSUE TITLE
Ticket status change email | does not send email of status change from "sent to channel" to "partially listed"

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#26]
No mail is received on changing the ticket status from "sent to channel" to "partially listed"

**Comment by Divyagawas** [comment]
Checked but still could not receive email for this condition
http://listr.ajency.in/catalog-channel-categories/index/156

**Comment by Divyagawas** [comment]
Cannot receive email for the status change : resubmitted to partially listed

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
Fixed.Thanx
