### ISSUE TITLE
Upload, edit mode and download status specific|if the status tab has sku's but is not editable - should show download and edit option

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#264]
Upload, edit mode and download status specific -if the status tab has sku's but is not editable - should show download and edit option.

But should not save any edited changes

AE is unable to see the download and edit mode buttons for following catalog status and sku's in the status
1. Review pending : - info pending and review pass sub tabs
2. Info pending with AE: - review pass sub tab
3. Resubmitted: - info pending and review pass sub tabs

LE is unable to see the download and edit mode buttons for following catalog status and sku's in the status
1. Draft: - All and error SKU's sub tabs
2. Review pending : - info pending and review pass sub tabs
3. info pending with AE :- review pass
4. Resubmitted:- Review pass - (cannot see the review pass SKU's)
5. partially listed:- Review pass

**Comment by robiulpro** [comment]
This was done according to the task assigned on asana: https://app.asana.com/0/229682126356060/227258480515821
