### ISSUE TITLE
LE| assigned to me catalogs | first shows only 2 pages -but after clicking shows 6 pages

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#266]
1. Login as robiul
2. go to http://listr.ajency.in/catalogs
3. click on 'Assigned to me' shows only 2 pages
![image](https://cloud.githubusercontent.com/assets/11714762/21590510/76128548-d122-11e6-9bcd-2312b33b159e.png)

4. click on 2nd page - Now shows 6 pages
![image](https://cloud.githubusercontent.com/assets/11714762/21590514/8513c7aa-d122-11e6-9da5-8d9831126158.png)

**Comment by robiulpro** [comment]
Fixed.
