### ISSUE TITLE
catalog listing | unassigned | shows all the catalogs when clicked on the next page

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#272]
1. Go on http://listr.ajency.in/catalogs
2. click on 'unassigned' tab - Can see all the unassigned catalogs
3. Now click on '2' on the page navigation bar on the bottom - Shows all the catalogs(Assigned & unassigned)
![image](https://cloud.githubusercontent.com/assets/11714762/21637429/d962a75c-d28c-11e6-8935-9c79afb331f7.png)

**Comment by robiulpro** [comment]
Fixed
