### ISSUE TITLE
Edit mode | When the sku status is "info pending with AE" AE cannot edit the sku

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#28]
In edit mode,  when the sku status is "info pending with AE" AE is not able to edit the sku

![image](https://cloud.githubusercontent.com/assets/11714762/19298401/f5b96634-906a-11e6-8639-e3a9742c0304.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
Fixed
