### ISSUE TITLE
Error text changes 

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#289]
Ex: Total 7 row has error and cannot be imported.

Should be: Total 7 rows have error/s and cannot be imported.

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
Chnages are not reflected. please checked
![image](https://cloud.githubusercontent.com/assets/11714762/21850314/06cffde0-d830-11e6-8ccd-1881ea146fe0.png)
