### ISSUE TITLE
AE is not able to select the sku's in "info pending with AE" status to move them to new catalog

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#29]
When the Catalog is in "info pending with AE" status, AE should be able to select the sku's whose status is "info pending with AE" and move them to other catalog or delete them using a button "move to new catalog" button and "delete"

![13](https://cloud.githubusercontent.com/assets/11714762/19298648/0253543e-906d-11e6-9474-3aa039a299fb.png)

In draft status
![image](https://cloud.githubusercontent.com/assets/11714762/19298685/2806e4a2-906d-11e6-81c2-14650f95b6cc.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
Fixed.Thanx
