### ISSUE TITLE
Wrong history text generated when catalog status is review pending

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#292]
Activity shows 'Catalog status changed from Review pending to Info pending with AE by Shruti Naik' when the status of the sku is changed to 'review pass' and the catalog status is 'review pending'
![image](https://cloud.githubusercontent.com/assets/11714762/21804152/7808e2f2-d753-11e6-8de4-36f3f1e75442.png)

**Comment by robiulpro** [comment]
Fixed
