### ISSUE TITLE
On changing the catalog status to 'review pass' - 'Tickets created' message comes as many times as many MP's are added

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#293]
On changing the catalog status to 'review pass' - 'Tickets created' message comes as many times as many MP's are added

Should come only once

Ticket/s created by Shruti Naik

![image](https://cloud.githubusercontent.com/assets/11714762/21804233/e96f17ea-d753-11e6-80c8-b634e716027b.png)

**Comment by robiulpro** [comment]
Fixed
