### ISSUE TITLE
When ticket status is changes to 'Info pending with AE' the submiting button gets stuck

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#297]
![image](https://cloud.githubusercontent.com/assets/11714762/21804979/cede3f4c-d757-11e6-9c8a-1e2d71159376.png)

**Comment by Divyagawas** [comment]
A blank entry in the history is generated for the same
![image](https://cloud.githubusercontent.com/assets/11714762/21805005/f7b34d36-d757-11e6-9df2-bf3bca78b47f.png)

**Comment by Divyagawas** [comment]
Same is noticed when status of ticket changed from "Resubmitted" to 'Seller panel down'
![image](https://cloud.githubusercontent.com/assets/11714762/21805113/6bae3de0-d758-11e6-9ae9-46adbfad109b.png)

**Comment by robiulpro** [comment]
Fixed
