### ISSUE TITLE
Remove the unwanted elements from the comments section for "catalog" and "tickets"

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#30]
Please remove all the elements marked in red from the comment section of "catalog" and "tickets"

![13](https://cloud.githubusercontent.com/assets/11714762/19299023/6217a9f4-906f-11e6-842c-025832c34732.png)

**Comment by robiulpro** [comment]
Removed Related discussion area, footer cannot be removed.

**Comment by Divyagawas** [comment]
Ok, thanx
