### ISSUE TITLE
LA cannot see the 'assigned to' name prepopulated in the assign feild | Assigned tickets & Overdue tickets tabs

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#305]
![2 no assignee name shows up](https://cloud.githubusercontent.com/assets/11714762/21848525/28fed0b6-d827-11e6-894d-36f995b243df.jpg)
![3 no assignee name shows up](https://cloud.githubusercontent.com/assets/11714762/21848527/297ab672-d827-11e6-8192-062cb77fad73.jpg)

**Comment by robiulpro** [comment]
Fixed
