### ISSUE TITLE
Excel sheet -Bug (Shows missing sku error for the sku's not present in the catalog)

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#308]
1. Open catalog in draft state
2. download only the sku's in 'sku's with error' 
3. upload the same sheet
4. shows 'missing sku and product name' message for the once which were not uploaded in this sheet
![image](https://cloud.githubusercontent.com/assets/11714762/21978425/92b2d2c8-dc00-11e6-8419-36ceadb228cf.png)

**Comment by robiulpro** [comment]
Fixed.
