### ISSUE TITLE
After auto rectification - The sku code shown on the sku listing page is shown without rectified data

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#315]
![image](https://cloud.githubusercontent.com/assets/11714762/22063729/6b5275c4-dda6-11e6-87d0-28597b7e4176.png)

**Comment by robiulpro** [comment]
I cant see anything wrong in the screenshot. underscore is not ignored, so definitely it will show.

**Comment by Divyagawas** [comment]
The spaces and other special characters in the sku was shown, wrong screen though. but the issue has been fixed now.Thanx
