### ISSUE TITLE
In parent sku -If a '-' is added -Shows message 'Invalid character found in parent sku code.'

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#325]
SKU summary mode - If we add a hyphen to a parent SKU (Say ZZ007 to make it ZZ-007) -> Then it says -> 
Invalid character found in sku code.
![image](https://cloud.githubusercontent.com/assets/11714762/22144526/08781e02-df24-11e6-9ea2-c1dc28639207.png)

**Comment by robiulpro** [comment]
Fixed.
