### ISSUE TITLE
If a new row mandatory feild is added in the category- On downloading the catalog associated with it, thows error

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#348]
1. Added a mandatory feild in the category - Fashion Mangalsutra's
2. Catalog associated with it - in status draft, review pass, partially listed
3. Trying to download the sheet from any above catalog throws error
http://listr.ajency.in/catalogs/download-filled-catalog-sheet/139/1/Jewellary%20Catalog/all
![image](https://cloud.githubusercontent.com/assets/11714762/22362968/d0214c40-e48c-11e6-8b3e-40e91b1a556c.png)

**Comment by robiulpro** [comment]
Couldn't reproduce the error
