### ISSUE TITLE
Remove the unwanted elements from the comments section on "sku"

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#36]
Please remove all the elements marked in red from the comment section of "sku"
![13](https://cloud.githubusercontent.com/assets/11714762/19304180/47ae9e28-9089-11e6-9efe-5c44468b0966.png)

**Comment by robiulpro** [comment]
Removed Related discussion area, footer cannot be removed.

**Comment by Divyagawas** [comment]
Ok.Thanx
