### ISSUE TITLE
When the catalog is in draft mode, LE,LA and CA should not be able to see the input box for path

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#39]
When the catalog is in draft mode, LE,LA and CA should not be able to see the input box for path as no one should be able to add the path and new market places rather than AE

![13](https://cloud.githubusercontent.com/assets/11714762/19308227/300599e4-909c-11e6-943d-81576a302789.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
Tested
