### ISSUE TITLE
From LA(Zeba's) account - if clicked on 'Admin' - shows a blank page (Should show users list as default)

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#397]
![image](https://cloud.githubusercontent.com/assets/11714762/23652261/39fac92c-034e-11e7-9e7d-9ab2b72d1142.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
http://listr.browntape.com/admin still can go to this page
