### ISSUE TITLE
Styling for notifications count tag and See all button 

### ISSUE THREAD

**Issue by ashika123** [ajency/Listr#451]
Styling for tag should be different for, Mark all seen button.
![styling](https://cloud.githubusercontent.com/assets/9797052/25181056/dce05f5c-252d-11e7-99f3-e3756ed9d9aa.jpg)

**Comment by ashika123** [comment]
@nevesseq  Both the button and the tag has the same styling still. Can you update what was the change made?

**Comment by anujkhurana** [comment]
@nevesseq Ashika has added similar comments on atleast two other issues.
Can you please help me understand why your fixes are not reflecting on the
test server?

**Comment by anujkhurana** [comment]
@Ashika please ensure there is detailed and explainatory comments from the
dev team on why same bugs are being reported twice.

**Comment by nevesseq** [comment]
i misunderstood that styling between count and see all button should be different, instead i fixed the padding

**Comment by ashika123** [comment]
Tested. Closed
