### ISSUE TITLE
User name is not shown in the list of notifications 

### ISSUE THREAD

**Issue by ashika123** [ajency/Listr#468]
Username is not shown when the ticket gets assigned in a notification 
![user name](https://cloud.githubusercontent.com/assets/9797052/25369996/53299126-29a5-11e7-91ab-ae4eeeeddeda.jpg)

**Comment by anujkhurana** [comment]
There was a bug around username not shown yesterday also. Maybe in the
conversation box. Doing bug fixes in multiple steps slows us down. Ideally
we should have put bug around notification and conversation box together.

Does the username come correctly in emails? Can we check other places where
it is expected to come.

**Comment by prajay04** [comment]
This issue occurred coz of the label comparison "Assigned To". In the code label was compared as  "Assigned to" with small t.

**Comment by anujkhurana** [comment]
@Prajay we need to work towards reducing the bugs that QA finds. You should
first use the feature you are submitting for QA. Ashika finding blockers
like this reflects poorly on the code quality and is not ok.

**Comment by ashika123** [comment]
Tested. Fixed

**Comment by prajay** [comment]
I think you meant to tag @prajay04 . I'm not part of this project.
