### ISSUE TITLE
Numeric validation message on single sku page is not shown for the uploaded catalog 

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#48]
1.the catalog sheet is uploaded with a numeric field with filled with some text.
2. Gets uploaded.
3. In the single sku page, it does not show an error message (does not highlight on the sku list also )

![13](https://cloud.githubusercontent.com/assets/11714762/19312869/efee8e18-90b1-11e6-81fa-2a9721cc0692.png)

**Comment by robiulpro** [comment]
0 is numeric

**Comment by Divyagawas** [comment]
Yes i know. But i have typed text i.e "opo"
