### ISSUE TITLE
Ticket listing | Ticket name font needs to be increased

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#54]
On ticket listing page,the font size of the ticket name needs to be bigger, can be same that of catalog name on catalog listing page.

![image](https://cloud.githubusercontent.com/assets/11714762/19375907/8fb16430-91f6-11e6-9b10-cd5bbeba46e3.png)

catalog listing page 
![image](https://cloud.githubusercontent.com/assets/11714762/19375973/2deb3bee-91f7-11e6-9d2f-237fa910d14c.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
Tested
