### ISSUE TITLE
Catalog> Download Excel Feature

### ISSUE THREAD

**Issue by ashika123** [ajency/Listr#60]
Currently the download excel feature downloads all the SKUs for all the users irrespective of the catalog status.

A dropdown can be provided for the Download Excel with dropdown values as 
- Current view
- All SKUs

**Comment by robiulpro** [comment]
Done

**Comment by Divyagawas** [comment]
Done and tested

**Comment by ashika123** [comment]
Required to highlight the SKUs in infor pending state
