### ISSUE TITLE
Listing tickets | The review buttons are shown for "unassigned" when clicking back from single ticket page to listing page

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#65]
1. Go to ticket listing page http://www.listr.ajency.in/listingTickets
2. under assign filter choose "me"
3. click on "review" button against the catalog to be reviewed
4. Now click on "back" arrow on the browser header to go back to the listing page.
5. gets you back to the listing page with filter assign set as "me" , but shows "unassigned" tickets with "review" button

![ui](https://cloud.githubusercontent.com/assets/11714762/19382929/e782547a-921f-11e6-9cfc-e60b09d3389b.png)

**Comment by robiulpro** [comment]
Fixed, now on click of back button, restrore the initial page load state

**Comment by Divyagawas** [comment]
OK thanx. Tested
