### ISSUE TITLE
After the seagate path is enter the "path" field input box is still show (should show a link)

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#69]
Once the seagate path is added - the path field should be shown as a link and not a input field (need to refresh the page to see the path as a link)

![image](https://cloud.githubusercontent.com/assets/11714762/19383862/19913996-9224-11e6-89ba-6a6237487613.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
Tested
