### ISSUE TITLE
Notification-For catalogs/tickets assigned  

### ISSUE THREAD

**Issue by ashika123** [ajency/Listr#72]
( To AE to for LE/LA whom it has been assigned  ,To LE/LA that they have been assigned)
Keeping the catalog info. content the same for all the 3 mails,
- to LA- about the creator's name and asignee's name
- to LE- about the creator's name
- to AE- about the asignee's name

**Comment by robiulpro** [comment]
Completed

**Comment by Divyagawas** [comment]
Tested for catalog
Tested for catalog - No mails are sent when a ticket is assigned

**Comment by Divyagawas** [comment]
Thanx
