### ISSUE TITLE
If a number is added in the numeric field of an SKU is shows a error message that " 'no.' is not a numeric feild"

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#77]
1. Create catalog, with some numeric feilds empty
2. Through sku summary try to add a number to that feild
3. Shows a error message ex: " 90 is not a number"

![37d6be7e-923a-11e6-80d8-4bb5fafd674e](https://cloud.githubusercontent.com/assets/11714762/19388003/19b46904-923b-11e6-89b2-8dedb3be1f71.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
Fixed
