### ISSUE TITLE
LA | catalog and ticket listing |  list of LE's under "assign to" action needs to be in alphabetic order

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#83]
![image](https://cloud.githubusercontent.com/assets/11714762/19427360/32b2054c-9461-11e6-8eb8-7b93c836238b.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
Some of the names are not displayed in alphabetic order on the top of the list, please check
