### ISSUE TITLE
Single sku page | The image on the left top is scrollable, needs to be sticky

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#85]
![image](https://cloud.githubusercontent.com/assets/11714762/19433448/62888918-947e-11e6-899f-67064e09e117.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
Tested.

The image seems sticky while scrolling down, but while scrolling up the section on the left breaks

![image](https://cloud.githubusercontent.com/assets/11714762/19520155/daee31fa-962c-11e6-991b-6060a41cf251.png)

**Comment by Divyagawas** [comment]
Fixed
