### ISSUE TITLE
Catalog/Ticket > Feature for LE to edit the assigned catalog or ticket

### ISSUE THREAD

**Issue by ashika123** [ajency/Listr#89]

**Comment by robiulpro** [comment]
Completed

**Comment by Divyagawas** [comment]
The channel listing id's for the sku's needs to be editable

![20](https://cloud.githubusercontent.com/assets/11714762/19547857/69e1742c-96b8-11e6-927e-d05a897c1d98.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
tested
