### ISSUE TITLE
Edit mode | Any LE can change the status of the sku's when the status is "review pending" or "resubmitted"

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#9]
Edit mode | Any LE can change the status of the sku's when the status is "review pending" or "resubmitted"

Expected : Only LE to whom the catalog is assigned can change the status of the sku when the catalog status is "review pending" or "resubmitted"

**Comment by robiulpro** [comment]
fixed

**Comment by Divyagawas** [comment]
Fixed
