### ISSUE TITLE
Option to Upload Excel File in Info. Pending state

### ISSUE THREAD

**Issue by ashika123** [ajency/Listr#90]
AE should be able to download catalog when the status is info pending and upload the same one again. Only the SKUs which are Info pending will get downloaded

**Comment by robiulpro** [comment]
Completed

**Comment by Divyagawas** [comment]
Tested.

The catalog is getting uploaded but for the sku's which were edited, the changes are not to be seen in the sku summary and edit mode

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
Tested.
