### ISSUE TITLE
LE should be able to upload catalog in Review pending, Resubmitted and partially listed

### ISSUE THREAD

**Issue by ashika123** [ajency/Listr#91]

**Comment by robiulpro** [comment]
Completed

**Comment by Divyagawas** [comment]
Tested.

The catalog is getting uploaded but for the sku's which were edited, the changes are not to be seen in the sku summary and edit mode

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
Tested.

Does not work for partially listed catalog still.

**Comment by robiulpro** [comment]
Fixed for partially listed catalog
