### ISSUE TITLE
'Back to catalog list' not required

### ISSUE THREAD

**Issue by ashika123** [ajency/Listr#95]
![back to catalog list](https://cloud.githubusercontent.com/assets/9797052/19474623/05ab51be-954e-11e6-8c42-6ca1e481a653.jpg)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
Tested.

Can you please get the catalog name a bit closer to the three tabs, Right now the catalog name seems to be floating
![19](https://cloud.githubusercontent.com/assets/11714762/19520083/7af38318-962c-11e6-9242-5a0f71fbad0d.png)

**Comment by Divyagawas** [comment]
Cannot see the change still
