### ISSUE TITLE
Edit mode | When the sku status is "re-submitted" and changed to "review pass" or "info pending with AE" the color of status doesn't change

### ISSUE THREAD

**Issue by Divyagawas** [ajency/Listr#97]
![image](https://cloud.githubusercontent.com/assets/11714762/19506268/a4d6a74a-95e7-11e6-87cf-c9652996f09d.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
Tested.

Works when status changed to "review pass" but does not change color when the status is changed to "info pending with AE"

![image](https://cloud.githubusercontent.com/assets/11714762/19519803/0bcc7ae0-962b-11e6-9f94-537b01242edf.png)

**Comment by Divyagawas** [comment]
Please check for info pending again, still not becoming red

**Comment by Divyagawas** [comment]
Done.tested
